# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(user_name: "lauren99", password: "password", first_name: "Lauren", last_name: "Carne", email: "laurencarne@email.com")
User.create(user_name: "ross99", password: "password", first_name: "Ross", last_name: "Mawdsley", email: "rossmawdsley@email.com")
User.create(user_name: "harry99", password: "password", first_name: "Harry", last_name: "Potter", email: "harrypostter@email.com")
User.create(user_name: "hermione99", password: "password", first_name: "Hermione", last_name: "Granger", email: "hermionegranger@email.com")
User.create(user_name: "ron99", password: "password", first_name: "Ron", last_name: "Weasley", email: "ronweasley@email.com")

Book.create(name: "Harry Potter and the Goblet of Fire", synopsis: "Harry, Ron and Hermione enter their fourth year at Hogwarts. After having a strange dream of the Dark Lord and his Death Eaters, Harry Potter awakes at the Weasleys' house where they shortly depart for the 422nd Quidditch World Cup. After the match, the camp is attacked by Death Eaters.", author: "J.K. Rowling", genre: "Fantasy")
Book.create(name: "Harry Potter and the Sorcerer's Stone", synopsis: "But not everything is quiet at Hogwarts as Harry suspects someone is planning to steal the sorcerer's stone. On his eleventh birthday, Harry Potter discovers that he is no ordinary boy. Hagrid, a beetle-eyed giant, tells Harry that he is a wizard and has a place at Hogwarts School of Witchcraft and Wizardry.", author: "J.K. Rowling", genre: "Fantasy")
Book.create(name: "Harry Potter and the Chamber of Secrets", synopsis: "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.", author: "J.K. Rowling", genre: "Fantasy")
Book.create(name: "Ready Player One", synopsis: "Eighteen-year-old Wade Watts is one of these people, and he has a mission: to find an Easter egg hidden inside the OASIS by its wackadoodle creator, James Halliday. In order to get to the egg, a player must first find three keys and unlock three gates.", author: "Ernest Cline", genre: "Science Fiction")
Book.create(name: "The Little Mermaid", synopsis: "This is the story of a little mermaid named Ariel, who dreams of going on land. When her father, King Triton, forbids her to go on land, Ariel visits Ursula who her father had banished. Even though she helps her get to land, what Ariel doesn't know is that Ursula has plans to destroy her to get revenge on her father.", author: "Hans Christian Andersen", genre: "Childhood Fiction")
Book.create(name: "We Love Mario", synopsis: "The essential unauthorized guide to everything Super Mario, loaded with facts, fun, and secrets from more than 35 years of the popular game. Celebrate the world's most famous plumber with this fantastic unofficial guide to gaming's greatest hero. Packed with illustrations, We Love Mario!", author: "Jon Hamblin", genre: "Computer Gaming")
Book.create(name: "Sapiens", synopsis: "The last dwarf species of humans died out 12,000 years ago. Homo sapiens conquered the world because of its unique language. The Cognitive Revolution occurred between 70,000 to 30,000 years ago. It allowed Homo sapiens to communicate at a level never seen before in language.", author: "Yuval Noah Harari", genre: "Popular Science")
Book.create(name: "Pride and Prejudice", synopsis: "Pride and Prejudice is a humorous story of love and life among English gentility during the Georgian era. Mr Bennet is an English gentleman living in Hartfordshire with his overbearing wife. The Bennets 5 daughters; the beautiful Jane, the clever Elizabeth, the bookish Mary, the immature Kitty and the wild Lydia.", author: "Jane Austin", genre: "Fiction")
Book.create(name: "War and Peace", synopsis: "War and Peace broadly focuses on Napoleon's invasion of Russia in 1812 and follows three of the most well-known characters in literature: Pierre Bezukhov, the illegitimate son of a count who is fighting for his inheritance and yearning for spiritual fulfillment", author: "Leo Tolstoy", genre: "Fiction")
Book.create(name: "Little Women", synopsis: "With their father fighting in the American Civil War, sisters Jo, Meg, Amy and Beth are at home with their mother, a very outspoken women for her time. The story tells of how the sisters grow up, find love and find their place in the world. Four sisters and their mother at home. Their father is fighting in the war.", author: "Louisa May Alcott", genre: "Fiction")
Book.create(name: "Three Sisters", synopsis: "In a small Russian town at the turn of the century, three sisters (Olga, Irina, and Masha) and their brother Andrei live, but dream daily of their return to their former home in Moscow, where life is charming and stimulatingly meaningful.", author: "Anton Chekhov", genre: "Play")
Book.create(name: "Of Mice and Men", synopsis: "Two migrant field workers in California on their plantation during the Great Depression—George Milton, an intelligent but uneducated man, and Lennie Small, a bulky, strong man but mentally disabled—are in Soledad on their way to another part of California.", author: "John Steinbeck", genre: "Fiction")
Book.create(name: "Taming of the Shrew", synopsis: "The Taming of the Shrew Plot Summary. Here is a brief plot summary of The Taming of the Shrew: A wealthy Padua merchant, Baptista, has two daughters. One day Lucentio, a student, comes to Padua, sees Bianca, the younger sister, and falls madly in love with her.", author: "William Shakespeare", genre: "Fiction")
Book.create(name: "The Bell Jar", synopsis: "The Bell Jar details the life of Esther Greenwood, a college student who dreams of becoming a poet. She is selected for a month-long summer internship as a guest editor of Ladies' Day magazine, but her time in New York City is unfulfilling as she struggles with issues of identity and societal norms.", author: "Sylvia Plath", genre: "Fiction")
Book.create(name: "The Bible", synopsis: "The Book of Genesis opens the Hebrew Bible with the story of creation. God, a spirit hovering over an empty, watery void, creates the world by speaking into the darkness and calling into being light, sky, land, vegetation, and living creatures over the course of six days.", author: "Jesus", genre: "Non-Fiction")
Book.create(name: "How to Win Friends and Influence People", synopsis: "The classic guide to greatly improving effectiveness and efficiency by mastering the ability to work with and through the people around you – by self-improvement guru, Dale Carnegie.", author: "Dale Carnegie", genre: "Lifestyle")

UserBook.create(user_id: 1, book_id: 1, read_status: "Completed", rating: 5, review: "Really good book, engaging and interesting! Can't wait for the next in the series!!!", possesion: true)
UserBook.create(user_id: 1, book_id: 2, read_status: "Completed", rating: 4, review: "Another great Potter book, not as good as the last but still loving it!", possesion: true)
UserBook.create(user_id: 1, book_id: 3, read_status: "Completed", rating: 5, review: "Love Potter!! J.K is a GENIUS!!", possesion: true)
UserBook.create(user_id: 1, book_id: 4, read_status: "Reading", rating: 3, review: "Really cool so far but a long start....will updated when I've finished the book.", possesion: true)
UserBook.create(user_id: 2, book_id: 5, read_status: "Reading", rating: 4, review: "Really engaging so far, can't wait to see how it ends.", possesion: true)
UserBook.create(user_id: 2, book_id: 6, read_status: "Completed", rating: 3, review: "Was alright, not bad at all just not very memorable.", possesion: true)
UserBook.create(user_id: 2, book_id: 7, read_status: "Completed", rating: 5, review: "SO SO SO Good, lots of twists and turns! I would reccommened to everyone!", possesion: true)
UserBook.create(user_id: 3, book_id: 8, read_status: "Completed", rating: 5, review: "A very long read but felt effortless. Would read all over again.", possesion: false)
UserBook.create(user_id: 3, book_id: 9, read_status: "Abandoned", rating: 1, review: "So dull! Very long winded. COuldn't finish....to BORING!!!", possesion: false)
UserBook.create(user_id: 4, book_id: 10, read_status: "Completed", rating: 4, review: "A good read, love this author.", possesion: false)
UserBook.create(user_id: 4, book_id: 11, read_status: "Completed", rating: 3, review: "Very interesting a good classic book but a little dated.", possesion: true)
UserBook.create(user_id: 4, book_id: 12, read_status: "Completed", rating: 5, review: "Great fun to read!", possesion: false)
UserBook.create(user_id: 4, book_id: 13, read_status: "Completed", rating: 5, review: "Amazing book, so insightful and relevant. Would read again and reccommend.", possesion: false)
UserBook.create(user_id: 4, book_id: 14, read_status: "Completed", rating: 4, review: "Long book but with lots of very interesting points raised.", possesion: false)
UserBook.create(user_id: 4, book_id: 15, read_status: "Completed", rating: 5, review: "Amazing!! Enought said...", possesion: true)
UserBook.create(user_id: 5, book_id: 16, read_status: "Abandoned", rating: 1, review: "So slow and hard to read. Not conversational at all.", possesion: false)
UserBook.create(user_id: 1, book_id: 16, read_status: "Unopened", rating: nil, review: "Tbc", possesion: true)
UserBook.create(user_id: 1, book_id: 15, read_status: "Completed", rating: 5, review: "Was great. Another classic added to my collection.", possesion: false)
UserBook.create(user_id: 2, book_id: 14, read_status: "Abandoned", rating: 1, review: "Bluh...", possesion: false)
UserBook.create(user_id: 2, book_id: 13, read_status: "Reading", rating: 3, review: "So far so good, I hope there are some twists to come.", possesion: true)
UserBook.create(user_id: 3, book_id: 12, read_status: "Unopened", rating: nil, review: "Tbc", possesion: true)
UserBook.create(user_id: 3, book_id: 11, read_status: "Completed", rating: 4, review: "Really nice read. Felt like a conversation throughout.", possesion: false)
UserBook.create(user_id: 3, book_id: 10, read_status: "Completed", rating: 5, review: "Good solid book. No complaints", possesion: false)
UserBook.create(user_id: 4, book_id: 9, read_status: "Reading", rating: 3, review: "Strong start, interesting characters.", possesion: true)
UserBook.create(user_id: 4, book_id: 8, read_status: "Completed", rating: 4, review: "Good book. Could have done with a better ending but still a good read.", possesion: true)
UserBook.create(user_id: 5, book_id: 7, read_status: "Abandoned", rating: 1, review: "To long...", possesion: false)
